### ISSUE TITLE
`'pip.installed' is not available` on `centos-6`

### ISSUE THREAD

**Issue by myii** [netmanagers/salt-image-builder#18]
https://travis-ci.org/myii/django-formula/jobs/616733137#L788-L794

```sls
       [DEBUG   ] Failed to import module pip:
       Traceback (most recent call last):
         File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1440, in _load_module
           mod = imp.load_module(mod_namespace, fn_, fpath, desc)
         File "/usr/lib/python2.7/site-packages/salt/modules/pip.py", line 86, in <module>
           import pkg_resources
       ImportError: No module named pkg_resources
```

https://travis-ci.org/myii/django-formula/jobs/616733137#L950-L958

```sls
       local:
       ----------
                 ID: django_pip
           Function: pip.installed
               Name: Django
             Result: False
            Comment: State 'pip.installed' was not found in SLS 'django.pip'
              Reason: 'pip.installed' is not available.
            Changes: 
```

https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources

* Tried out some of the answers here but didn't make any progress

**Comment by myii** [comment]
@javierbertoli Excellent, that's working fine now:

* https://travis-ci.org/myii/django-formula/jobs/617673128

**Comment by javierbertoli** [comment]
Great!
