### ISSUE TITLE
`NameError: name 'pip' is not defined` on `opensuse-leap-42-2018-3-py2`

### ISSUE THREAD

**Issue by myii** [netmanagers/salt-image-builder#3]
Following on from #2, tried `opensuse-leap-42-2018-3-py2` instead.  Ended up with a different error, even after retrying.

https://travis-ci.com/myii/postgres-formula/builds/110123552#L1135

```
       [ERROR   ] Failed to import states pip_state, this is due most likely to a syntax error:
       Traceback (most recent call last):
         File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1534, in _load_module
           mod = imp.load_module(mod_namespace, fn_, fpath, desc)
         File "/usr/lib/python2.7/site-packages/salt/states/pip_state.py", line 63, in <module>
           del pip
       NameError: name 'pip' is not defined
```

Strange, because `2017.7` is working fine:

* https://travis-ci.com/saltstack-formulas/postgres-formula/jobs/196624899

**Comment by myii** [comment]
Forgot to mention, even stranger because the previous near-identical image (`opensuse-423-2018-3-py2`) has been working:

* https://travis-ci.com/saltstack-formulas/postgres-formula/jobs/196669460

**Comment by myii** [comment]
Some good news is that this is working on the `template-formula`:

* https://travis-ci.org/myii/template-formula/jobs/526626069

**Comment by myii** [comment]
Closing since this version of `opensuse-leap` is now EOL.
